apiVersion: v1
kind: ConfigMap
metadata:
  name: micro-mall-config
  namespace: micro-mall
data:
  jaeger-host: "jaeger-service"
  jaeger-port: "14268"
  mysql-user: "root"
  mysql-password: "SecretKey"
  mysql-host: "mysql-service"
  mysql-port: "3306"
  redis-host: "redis-service"
  redis-port: "6379"