apiVersion: v1
kind: ServiceAccount
metadata:
  name: micro-mall
  namespace: micro-mall


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: micro-mall
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - list
      - patch
      - watch


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: micro-mall
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: micro-mall
subjects:
  - kind: ServiceAccount
    name: micro-mall
    namespace: micro-mall

