// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Uid      uint64 `json:"uid"`
	Username string `json:"username"`
}

type LoginReq struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	User         User   `json:"user"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	UserName        string `json:"username"`
	Password        string `json:"password"`
	PasswordConfirm string `json:"passwordConfirm"`
}

type BaseResp struct {
	Message string `json:"message"`
}

type GetUserReq struct {
	Uid uint64 `path:"uid"`
}

type GetUserResp struct {
	Message string `json:"message"`
	User    User   `json:"user"`
}

type Stock struct {
	StockId int64 `json:"stockId"`
	GoodsId int64 `json:"goodsId"`
	Count   int64 `json:"count"`
}

type CreateStockReq struct {
	GoodsId int64 `json:"goodsId"`
	Count   int64 `json:"count"`
}

type CreateStockResp struct {
	StockId int64  `json:"stockId"`
	Message string `json:"message"`
}

type UpdateStockReq struct {
	StockId int64 `json:"stockId"`
	GoodsId int64 `json:"goodsId"`
	Count   int64 `json:"count"`
}

type UpdateStockResp struct {
	Message string `json:"message"`
}

type GetStockReq struct {
	StockId int64 `path:"stockId"`
}

type GetStockResp struct {
	Message string `json:"message"`
	Stock   Stock  `json:"stock"`
}

type Activity struct {
	Id             int64   `json:"activityId"`
	ActivityName   string  `json:"activityName"`
	GoodsId        int64   `json:"goodsId"`
	StockId        int64   `json:"stockId"`
	StartTime      int64   `json:"startTime"`
	EndTime        int64   `json:"endTime"`
	Total          int64   `json:"total"`
	Status         int64   `json:"status"`
	BuyLimit       int64   `json:"buyLimit"`
	BuyProbability float64 `json:"buyProbability"`
}

type CreateActivityReq struct {
	ActivityName   string  `json:"activityName"`
	GoodsId        int64   `json:"goodsId"`
	StockId        int64   `json:"stockId"`
	StartTime      int64   `json:"startTime"`
	EndTime        int64   `json:"endTime"`
	Total          int64   `json:"total"`
	Status         int64   `json:"status"`
	BuyLimit       int64   `json:"buyLimit"`
	BuyProbability float64 `json:"buyProbability"`
}

type CreateActivityResp struct {
	Message    string `json:"message"`
	ActivityId int64  `json:"activityId"`
}

type UpdateActivityReq struct {
	Id             int64   `json:"activityId"`
	ActivityName   string  `json:"activityName"`
	GoodsId        int64   `json:"goodsId"`
	StockId        int64   `json:"stockId"`
	StartTime      int64   `json:"startTime"`
	EndTime        int64   `json:"endTime"`
	Total          int64   `json:"total"`
	Status         int64   `json:"status"`
	BuyLimit       int64   `json:"buyLimit"`
	BuyProbability float64 `json:"buyProbability"`
}

type UpdateActivityResp struct {
	Message string `json:"message"`
}

type GetActivityReq struct {
	ActivityId int64 `path:"activityId"`
}

type GetActivityResp struct {
	Message  string   `json:"message"`
	Activity Activity `json:"activity"`
}

type SeckillReq struct {
	Uid        int64 `json:"uid"`
	ActivityId int64 `json:"activityId"`
	GoodsId    int64 `json:"goodsId"`
	StockId    int64 `json:"stockId"`
	BuyCnt     int64 `json:"buyCnt"`
	AccessTime int64 `json:"accessTime"`
}

type SeckillResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}
