// Code generated by goctl. DO NOT EDIT!
// Source: stock.proto

package stockclient

import (
	"context"

	"seckill/service/stock"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeductStockReq  = stock.DeductStockReq
	DeductStockResp = stock.DeductStockResp

	Stock interface {
		DeductStock(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error)
		DeductStockRevert(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error)
		DeductStockFast(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error)
		DeductStockFastRevert(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error)
	}

	defaultStock struct {
		cli zrpc.Client
	}
)

func NewStock(cli zrpc.Client) Stock {
	return &defaultStock{
		cli: cli,
	}
}

func (m *defaultStock) DeductStock(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error) {
	client := stock.NewStockClient(m.cli.Conn())
	return client.DeductStock(ctx, in, opts...)
}

func (m *defaultStock) DeductStockRevert(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error) {
	client := stock.NewStockClient(m.cli.Conn())
	return client.DeductStockRevert(ctx, in, opts...)
}

func (m *defaultStock) DeductStockFast(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error) {
	client := stock.NewStockClient(m.cli.Conn())
	return client.DeductStockFast(ctx, in, opts...)
}

func (m *defaultStock) DeductStockFastRevert(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error) {
	client := stock.NewStockClient(m.cli.Conn())
	return client.DeductStockFastRevert(ctx, in, opts...)
}
