// Code generated by goctl. DO NOT EDIT!
// Source: seckill.proto

package server

import (
	"context"

	"seckill/internal/logic"
	"seckill/internal/svc"
	"seckill/service/seckill"
)

type SeckillServer struct {
	svcCtx *svc.ServiceContext
	seckill.UnimplementedSeckillServer
}

func NewSeckillServer(svcCtx *svc.ServiceContext) *SeckillServer {
	return &SeckillServer{
		svcCtx: svcCtx,
	}
}

func (s *SeckillServer) Seckill(ctx context.Context, in *seckill.SeckillReq) (*seckill.BaseSeckillResp, error) {
	l := logic.NewSeckillLogic(ctx, s.svcCtx)
	return l.Seckill(in)
}

func (s *SeckillServer) Seckill2(ctx context.Context, in *seckill.SeckillReq) (*seckill.BaseSeckillResp, error) {
	l := logic.NewSeckill2Logic(ctx, s.svcCtx)
	return l.Seckill2(in)
}
